# Generated by Django 4.2.13 on 2024-05-12 16:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalsitter',
            name='Arrival_Time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='arrivalsitter',
            name='Arrival_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 16, 45, 11, 473321, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 16, 45, 11, 476346, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sitter_registration',
            name='Date_of_birth',
            field=models.DateField(),
        ),
    ]
