# Generated by Django 4.2.13 on 2024-05-12 17:06

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0006_rename_arrival_date_babie_registration_arrival_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babie_registration',
            name='Arrival_time',
        ),
        migrations.AddField(
            model_name='babie_registration',
            name='Arrival_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 6, 18, 611468, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 6, 18, 614471, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sitter_registration',
            name='Gender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AddField(
            model_name='babie_registration',
            name='Arrival_Time',
            field=models.TimeField(default=datetime.datetime(2024, 5, 12, 17, 6, 18, 595058, tzinfo=datetime.timezone.utc)),
        ),
    ]
