# Generated by Django 4.2.13 on 2024-05-13 05:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0009_rename_amount_received_sellingdoll_unit_price_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 5, 39, 41, 523344, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 13, 5, 39, 41, 525348, tzinfo=datetime.timezone.utc)),
        ),
    ]
