# Generated by Django 4.2.13 on 2024-05-14 21:13

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0010_alter_procurement_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babie_registration',
            name='is_assigned',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 21, 13, 43, 269074, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 14, 21, 13, 43, 271001, tzinfo=datetime.timezone.utc)),
        ),
    ]
