# Generated by Django 4.2.13 on 2024-05-18 11:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0012_remove_babie_registration_is_assigned_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypayment',
            name='status',
            field=models.CharField(blank=True, choices=[('complete', 'Complete'), ('pending', 'Pending')], max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='babie_registration',
            name='Gender',
            field=models.CharField(choices=[('', '--select--'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 18, 11, 56, 39, 922458, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='item_name',
            field=models.CharField(choices=[('', '--select--'), ('Fruits', 'Fruits'), ('Diapers', 'Diapers'), ('Milk', 'Milk'), ('Toys', 'Toys')], max_length=100),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 18, 11, 56, 39, 925150, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sitter_registration',
            name='Gender',
            field=models.CharField(choices=[('', '--select--'), ('Male', 'Male'), ('Female', 'Female')], max_length=10),
        ),
        migrations.AlterField(
            model_name='sitter_registration',
            name='Level_of_education',
            field=models.CharField(choices=[('', '--select--'), ('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Other', 'Other')], max_length=100),
        ),
    ]
