# Generated by Django 4.2.13 on 2024-05-19 17:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0013_babypayment_status_alter_babie_registration_gender_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellingdoll',
            name='total_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='status',
            field=models.CharField(choices=[('complete', 'Complete'), ('pending', 'Pending')], default='pending', max_length=10),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 17, 57, 42, 40369, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 19, 17, 57, 42, 41958, tzinfo=datetime.timezone.utc)),
        ),
    ]
