# Generated by Django 4.2.13 on 2024-07-26 15:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daycare_app", "0015_alter_arrivalsitter_status_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurement",
            name="Date_of_purchase",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 26, 15, 58, 43, 724830, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="sellingdoll",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 7, 26, 15, 58, 43, 726688, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
