# Generated by Django 4.2.13 on 2024-05-08 13:34

import datetime
import daycare_app.models
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Arrivalsitter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Sitter_Number', models.CharField(default=0, max_length=200)),
                ('Arrival_Date', models.DateField(default=django.utils.timezone.now)),
                ('Status', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Babie_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Baby_Name', models.CharField(max_length=200, validators=[daycare_app.models.validate_letters])),
                ('Baby_No', models.CharField(max_length=200, null=True, unique=True)),
                ('Age', models.IntegerField(default=0)),
                ('Gender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10)),
                ('Location', models.CharField(max_length=80)),
                ('Parent_name', models.CharField(max_length=100, validators=[daycare_app.models.validate_letters])),
                ('Brought_by', models.CharField(max_length=200, validators=[daycare_app.models.validate_letters])),
                ('Arrival_Time', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='BabyPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('payment_date', models.DateField()),
                ('full_day', models.BooleanField(default=False)),
                ('half_day', models.BooleanField(default=False)),
                ('monthly', models.BooleanField(default=False)),
                ('total_amount_due', models.DecimalField(decimal_places=2, max_digits=10)),
                ('amount_paid', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Categorystay',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Issueout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_issued_out', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='PaymentRate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Procurement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(choices=[('Fruits', 'Fruits'), ('Diapers', 'Diapers'), ('Milk', 'Milk'), ('Toys', 'Toys')], max_length=100)),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('quantity_received', models.IntegerField(blank=True, default=0, null=True)),
                ('Total_amount', models.IntegerField(blank=True, default=0, null=True)),
                ('Date_of_purchase', models.DateField(default=datetime.datetime(2024, 5, 8, 13, 34, 52, 131172, tzinfo=datetime.timezone.utc))),
                ('quantity_issued_out', models.IntegerField(blank=True, default=0, null=True)),
                ('stock_at_hand', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sitter_registration',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Name', models.CharField(max_length=200, validators=[daycare_app.models.validate_letters])),
                ('Sitter_No', models.CharField(max_length=500, null=True, unique=True)),
                ('Sitter_Contact', models.CharField(max_length=10, validators=[daycare_app.models.validate_contacts])),
                ('Location', models.CharField(default='Kabalagala', max_length=10)),
                ('Date_of_birth', models.DateField(default=django.utils.timezone.now)),
                ('Gender', models.CharField(max_length=10)),
                ('Next_of_kin', models.CharField(max_length=100, validators=[daycare_app.models.validate_letters])),
                ('NIN', models.CharField(max_length=14, validators=[daycare_app.models.validate_NIN])),
                ('Recommenders_name', models.CharField(max_length=200, validators=[daycare_app.models.validate_letters])),
                ('Recommenders_contact', models.CharField(max_length=10, validators=[daycare_app.models.validate_contacts])),
                ('Religion', models.CharField(blank=True, max_length=20, null=True, verbose_name='Religion (Optional)')),
                ('Level_of_education', models.CharField(choices=[('Certificate', 'Certificate'), ('Diploma', 'Diploma'), ('Degree', 'Degree'), ('Other', 'Other')], max_length=100)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='Stock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(blank=True, max_length=100, null=True)),
                ('total_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('recieved_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('unit_price', models.IntegerField(blank=True, default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='SitterPayment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_date', models.DateField(default=django.utils.timezone.now)),
                ('babies_attended', models.PositiveIntegerField(default=0)),
                ('amount_paid', models.IntegerField(default=3000)),
                ('sitter', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare_app.arrivalsitter')),
            ],
        ),
        migrations.CreateModel(
            name='Sellingdoll',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('amount_received', models.IntegerField(blank=True, default=0, null=True)),
                ('issued_to', models.CharField(blank=True, max_length=100, null=True)),
                ('sold_quantity', models.IntegerField(blank=True, default=0, null=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare_app.stock')),
            ],
        ),
        migrations.CreateModel(
            name='Baby_departure',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('departure_time', models.DateTimeField()),
                ('person_taking_baby', models.CharField(max_length=100, validators=[daycare_app.models.validate_letters])),
                ('comment', models.TextField(blank=True, verbose_name='Comment (Optional)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('baby_name', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare_app.babie_registration')),
            ],
        ),
        migrations.AddField(
            model_name='babie_registration',
            name='Period_of_stay',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='daycare_app.categorystay'),
        ),
        migrations.AddField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare_app.babie_registration'),
        ),
        migrations.AddField(
            model_name='arrivalsitter',
            name='Sitter_name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare_app.sitter_registration'),
        ),
    ]
