# Generated by Django 4.2.13 on 2024-05-08 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 18, 42, 5, 729364, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
            field=models.ManyToManyField(blank=True, to='daycare_app.babie_registration'),
        ),
    ]
