# Generated by Django 4.2.13 on 2024-05-08 18:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0002_remove_arrivalsitter_assigned_babies_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 18, 42, 37, 114967, tzinfo=datetime.timezone.utc)),
        ),
    ]
