# Generated by Django 4.2.13 on 2024-05-08 19:23

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0003_alter_procurement_date_of_purchase'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 8, 19, 23, 54, 351501, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare_app.babie_registration'),
        ),
    ]
