# Generated by Django 4.2.13 on 2024-05-12 17:01

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0004_alter_arrivalsitter_arrival_date_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babie_registration',
            name='Arrival_Time',
        ),
        migrations.AlterField(
            model_name='arrivalsitter',
            name='Arrival_Date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='babie_registration',
            name='Arrival_Date',
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 1, 39, 887254, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 1, 39, 889843, tzinfo=datetime.timezone.utc)),
        ),
    ]
