# Generated by Django 4.2.13 on 2024-05-09 05:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0004_remove_arrivalsitter_assigned_babies_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='arrivalsitter',
            name='Total_Babies_Attended',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 5, 29, 47, 220016, tzinfo=datetime.timezone.utc)),
        ),
    ]
