# Generated by Django 4.2.13 on 2024-05-12 17:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0005_remove_babie_registration_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='babie_registration',
            old_name='Arrival_Date',
            new_name='Arrival_time',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 2, 59, 175117, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 17, 2, 59, 177641, tzinfo=datetime.timezone.utc)),
        ),
    ]
