# Generated by Django 4.2.13 on 2024-05-09 05:41

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0005_arrivalsitter_total_babies_attended_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='arrivalsitter',
            name='Total_Babies_Attended',
        ),
        migrations.RemoveField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 5, 41, 19, 554316, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AddField(
            model_name='arrivalsitter',
            name='Assigned_Babies',
            field=models.ManyToManyField(blank=True, to='daycare_app.babie_registration'),
        ),
    ]
