# Generated by Django 4.2.13 on 2024-05-09 13:21

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0007_alter_procurement_date_of_purchase'),
    ]

    operations = [
        migrations.AddField(
            model_name='babypayment',
            name='remaining_balance',
            field=models.DecimalField(blank=True, decimal_places=2, default=False, max_digits=10),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 13, 21, 1, 390287, tzinfo=datetime.timezone.utc)),
        ),
    ]
