# Generated by Django 4.2.13 on 2024-05-12 18:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0008_remove_babie_registration_arrival_time_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='sellingdoll',
            old_name='amount_received',
            new_name='unit_price',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 18, 57, 34, 408286, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 12, 18, 57, 34, 409295, tzinfo=datetime.timezone.utc)),
        ),
    ]
