# Generated by Django 4.2.13 on 2024-05-09 13:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0008_babypayment_remaining_balance_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='full_day',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='half_day',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='monthly',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='babypayment',
            name='total_amount_due',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 9, 13, 29, 24, 625853, tzinfo=datetime.timezone.utc)),
        ),
    ]
