# Generated by Django 4.2.13 on 2024-05-16 14:47

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0011_babie_registration_is_assigned_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babie_registration',
            name='is_assigned',
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 14, 47, 21, 942106, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 16, 14, 47, 21, 943168, tzinfo=datetime.timezone.utc)),
        ),
    ]
