# Generated by Django 4.2.13 on 2024-05-10 05:42

import datetime
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0012_rename_arrival_time_babie_registration_arrival_date_and_time_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='babie_registration',
            name='Arrival_Date_and_Time',
        ),
        migrations.AddField(
            model_name='babie_registration',
            name='Arrival_Date',
            field=models.DateField(default=django.utils.timezone.now),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 5, 42, 45, 388061, tzinfo=datetime.timezone.utc)),
        ),
    ]
