# Generated by Django 4.2.13 on 2024-05-10 11:52

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0013_remove_babie_registration_arrival_date_and_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 11, 52, 23, 18748, tzinfo=datetime.timezone.utc)),
        ),
    ]
