# Generated by Django 4.2.13 on 2024-05-10 17:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0015_alter_procurement_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='name',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='daycare_app.babie_registration'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 17, 46, 31, 721763, tzinfo=datetime.timezone.utc)),
        ),
    ]
