# Generated by Django 4.2.13 on 2024-10-28 11:18

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("daycare_app", "0016_alter_procurement_date_of_purchase_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="procurement",
            name="Date_of_purchase",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 10, 28, 11, 18, 31, 196111, tzinfo=datetime.timezone.utc
                )
            ),
        ),
        migrations.AlterField(
            model_name="sellingdoll",
            name="date",
            field=models.DateField(
                default=datetime.datetime(
                    2024, 10, 28, 11, 18, 31, 197111, tzinfo=datetime.timezone.utc
                )
            ),
        ),
    ]
