# Generated by Django 4.2.13 on 2024-05-10 18:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0019_alter_procurement_date_of_purchase'),
    ]

    operations = [
        migrations.AlterField(
            model_name='babypayment',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 10, 18, 2, 57, 456402, tzinfo=datetime.timezone.utc)),
        ),
    ]
