# Generated by Django 4.2.13 on 2024-05-11 12:19

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0021_alter_procurement_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='doll_image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 12, 19, 55, 122613, tzinfo=datetime.timezone.utc)),
        ),
    ]
