# Generated by Django 4.2.13 on 2024-05-11 19:12

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('daycare_app', '0024_currency_alter_procurement_date_of_purchase_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='stock',
            name='currency',
        ),
        migrations.AddField(
            model_name='sellingdoll',
            name='date',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 19, 12, 1, 300398, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='procurement',
            name='Date_of_purchase',
            field=models.DateField(default=datetime.datetime(2024, 5, 11, 19, 12, 1, 297332, tzinfo=datetime.timezone.utc)),
        ),
        migrations.AlterField(
            model_name='stock',
            name='unit_price',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
